CREATE TABLE AREA(
NUMERO_AREA INT NOT NULL,
NOMBRE_AREA VARCHAR(15) NOT NULL
);

CREATE TABLE EMPLEADO (
CEDULA_EMPLEADO VARCHAR 15 NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL, 
FECHA_NCTO DATE,
FECHA_INGRESO DATE,
DIRECCION VARCHAR(30),
SALARIO FLOAT,
ANNOS_EXPERIENCIA INT,
ACTIVO BOOLEAN,
SEXO VARCHAR(1),
FK_NUMERO_AREA INT NOT NUL
);

CREATE TABLE JEFE(
FK_NUMERO_AREA INT NOT NULL,
FK_CEDULA_EMPLEADO VARCHAR(15) NOT NULL,
FECHA_INICIO DATE,
FECHA_FIN DATE,
ESTADO VARCHAR(9) NOT NULL
);

CREATE TABLE PROYECTO(
NUMERO_PROYECTO INT NOT NULL,
NOMBRE_PROYECTO VARCHAR(15) NOT NULL
DESCRIPCION VARCHAR(60)
);

CREATE TABLE EMPLEADO_PROYECTO(
FK_CEDULA_EMPLEADO VARCHAR(15) NOT NULL,
FK_NUMERO_PROYECTO INT NOT NULL,
HORAS_TRABAJADAS FLOAT NOT NULL,
FECHA_TRABAJO DATETIME,
);

CREATE TABLE DEPENDIENTE(
CEDULA_DEPENDIENTE VARCHAR(15) NOT NULL,
NOMBRE_DEPENDIENTE VARCHA(60) NOT NULL,
SEXO VARCHAR(1),
FECHA_NCTO DATE,
PARENTESCO VARCHAR(8),
FK_CEDULA_EMPLEADO VARCHAR(15) NO NULL
);


ALTER TABLE EMPLEADO ADD PRIMARY KEY(CEDULA_EMPLEADO);

ALTER TABLE AREA ADD PRIMARY KEY (NUMERO_AREA);
ALTER TABLE EMPLEADO ADD FOREIGN KEY(FK_NUMERO_AREA) REFERENCES AREA(NUMERO_AREA) ;

ALTER TABLE JEFE ADD PRIMARY KEY(FK_NUMERO_AREA,FK_CEDULA_EMPLEADO) ;
ALTER TABLE JEFE ADD FOREIGN KEY(FK_NUMERO_AREA) REFERENCES AREA(NUMERO_AREA) ;
ALTER TABLE JEFE ADD FOREIGN KEY(FK_CEDULA_EMPLEADO) REFERENCES EMPLEADO(CEDULA_EMPLEADO) ;

ALTER TABLE PROYECTO ADD PRIMARY KEY(NUMERO_PROYECTO);

ALTER TABLE EMPLEADO_PROYECTO ADD PRIMARY KEY(FK_CEDULA_EMPLEADO, FK_NUMERO_PROYECTO);
ALTER TABLE EMPLEADO_PROYECTO ADD FOREIGN KEY(FK_CEDULA_EMPLEADO) REFERENCES EMPLEADO(CEDULA_EMPLEADO);
ALTER TABLE EMPLEADO_PROYECTO ADD FOREIGN KEY(FK_NUMERO_PROYECTO) REFERENCES PROYECTO(NUMERO_PROYECTO);

ALTER TABLE DEPENDIENTE ADD PRIMARY KEY(CEDULA_DEPENDIENTE);
ALTER TABLE DEPENDIENTE ADD FOREIGN KEY(FK_CEDULA_EMPLEADO) REFERENCES EMPLEADO(CEDULA_EMPLEADO);
